baseURL: http://example.org/
languageCode: en-us
title: Robotic Arm Mixed & Simple Computer Vision
theme:  Papermod

menu:
  main:
    - identifier: team member 1
      name: Xiayu Zeng
      url: https://github.com/Xiaayu/ese5190-final-project
      weight: 20
    - identifier: team member 2
      name: Yihan Wang
      url: https://github.com/WenyuWang1
      weight: 30
    - identifier: team member 
      name: Team Review
      url: https://github.com/orgs/Teddybearxy/repositories
      weight: 10

params:
  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true